import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Save } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { ImageDropzone } from '../components/ImageDropzone';
import { toast } from 'sonner';
import { propertyTypes } from '../data/mockData';
import { insertListing } from '../lib/supabase';

export default function CreateListing({ user, listings, onUpdateListings, onRefreshListings }) {
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [images, setImages] = useState([]);
  const [form, setForm] = useState({
    category: 'sale',
    type: '',
    rooms: '',
    area: '',
    floor: '',
    totalFloors: '',
    price: '',
    location: '',
    description: '',
    phone: user?.phone || ''
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!form.type || !form.price || !form.location) {
      toast.error('Bütün zəruri sahələri doldurun');
      return;
    }

    // Image validation - optional for now (test without images)
    // if (images.length === 0) {
    //   toast.error('Ən azı bir şəkil yükləyin');
    //   return;
    // }

    setIsSubmitting(true);

    try {
      // Prepare data for Supabase database - matching exact table schema
      // Table columns: id, title, description, images, category, type, price, currency, location, 
      // address, latitude, longitude, rooms, area, floor, total_floors, owner_type, agency_id, 
      // agency_name, owner_name, owner_phone, owner_email, user_id, complex_id, is_vip, is_agency, 
      // is_active, is_verified, amenities, created_at, updated_at, vip_until
      
      const listingData = {
        // Basic info
        title: `${form.type} - ${form.location}`,
        description: form.description || null,
        images: images.length > 0 ? images.map(img => img.publicUrl) : [],
        
        // Category must be: 'sale', 'rent', or 'daily'
        category: form.category, // Already one of: sale, rent, daily
        type: form.type,
        
        // Pricing
        price: parseFloat(form.price) || 0,
        currency: 'AZN',
        
        // Location
        location: form.location,
        address: null,
        latitude: null,
        longitude: null,
        
        // Property details
        rooms: form.rooms ? parseInt(form.rooms) : null,
        area: form.area ? parseFloat(form.area) : null,
        floor: form.floor ? parseInt(form.floor) : null,
        total_floors: form.totalFloors ? parseInt(form.totalFloors) : null,
        
        // Owner info - owner_type: 'agency' or 'sahibinden'
        owner_type: 'sahibinden', // User listings are 'sahibinden'
        owner_name: user?.name || 'İstifadəçi',
        owner_phone: form.phone || null,
        owner_email: user?.email || null,
        user_id: null, // Set to null for now since DB expects UUID format
        
        // Agency info (null for user listings)
        agency_id: null,
        agency_name: null,
        
        // Complex info
        complex_id: null,
        
        // Status flags
        is_vip: false,
        is_agency: false,
        is_active: true,
        is_verified: false,
        
        // Amenities
        amenities: [],
        
        // VIP expiration
        vip_until: null
        
        // Note: id, created_at, updated_at are auto-generated by Supabase
      };

      console.log('Inserting listing to Supabase:', listingData);

      // Insert into Supabase database
      const insertedListing = await insertListing(listingData);
      
      console.log('Listing inserted successfully:', insertedListing);

      // Also update local state for immediate UI feedback
      const localListing = {
        id: insertedListing.id,
        ...form,
        rooms: parseInt(form.rooms) || 0,
        area: parseInt(form.area) || 0,
        floor: parseInt(form.floor) || 0,
        totalFloors: parseInt(form.totalFloors) || 0,
        price: parseInt(form.price) || 0,
        images: images.map(img => img.publicUrl),
        isVip: false,
        isAgency: false,
        agencyId: null,
        agencyName: null,
        userId: user?.id,
        ownerType: 'sahibinden',
        createdAt: new Date().toISOString().split('T')[0]
      };

      onUpdateListings([localListing, ...listings]);
      
      // Refresh listings from database if callback exists
      if (onRefreshListings) {
        onRefreshListings();
      }

      toast.success('Elan uğurla Supabase-ə əlavə edildi!');
      navigate('/');
    } catch (error) {
      console.error('Error creating listing:', error);
      toast.error(`Xəta: ${error.message || 'Elan əlavə edilə bilmədi'}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50" data-testid="create-listing-page">
      <header className="sticky top-0 z-50 bg-white border-b">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 text-gray-600 hover:text-[#B91C1C]">
            <ArrowLeft size={20} />
            <span>Geri</span>
          </Link>
          <span className="logo-text text-2xl font-semibold text-[#B91C1C]">Mydom</span>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold text-gray-900 logo-text mb-8">Yeni Elan Yerləşdir</h1>

        <form onSubmit={handleSubmit} className="space-y-8">
          {/* Images */}
          <div className="bg-white rounded-xl p-6 border">
            <h2 className="text-lg font-semibold mb-4">Şəkillər</h2>
            <ImageDropzone images={images} onImagesChange={setImages} maxFiles={5} />
          </div>

          {/* Basic Info */}
          <div className="bg-white rounded-xl p-6 border">
            <h2 className="text-lg font-semibold mb-4">Əsas Məlumatlar</h2>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Kateqoriya *</Label>
                <Select value={form.category} onValueChange={(v) => setForm({...form, category: v})}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="sale">Satış</SelectItem>
                    <SelectItem value="rent">Kirayə (aylıq)</SelectItem>
                    <SelectItem value="daily">Günlük kirayə</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Əmlak növü *</Label>
                <Select value={form.type} onValueChange={(v) => setForm({...form, type: v})}>
                  <SelectTrigger><SelectValue placeholder="Seçin" /></SelectTrigger>
                  <SelectContent>
                    {propertyTypes.map(t => (
                      <SelectItem key={t.id} value={t.label}>{t.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Qiymət (AZN) *</Label>
                <Input type="number" value={form.price} onChange={(e) => setForm({...form, price: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Otaq sayı</Label>
                <Input type="number" value={form.rooms} onChange={(e) => setForm({...form, rooms: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Sahə (m²)</Label>
                <Input type="number" value={form.area} onChange={(e) => setForm({...form, area: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Mərtəbə</Label>
                <div className="flex gap-2">
                  <Input type="number" placeholder="Mərtəbə" value={form.floor} onChange={(e) => setForm({...form, floor: e.target.value})} />
                  <Input type="number" placeholder="Ümumi" value={form.totalFloors} onChange={(e) => setForm({...form, totalFloors: e.target.value})} />
                </div>
              </div>
            </div>
          </div>

          {/* Location & Contact */}
          <div className="bg-white rounded-xl p-6 border">
            <h2 className="text-lg font-semibold mb-4">Ünvan və Əlaqə</h2>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>Ünvan *</Label>
                <Input value={form.location} onChange={(e) => setForm({...form, location: e.target.value})} placeholder="Rayon, küçə, ev nömrəsi" />
              </div>
              <div className="space-y-2">
                <Label>Telefon *</Label>
                <Input value={form.phone} onChange={(e) => setForm({...form, phone: e.target.value})} placeholder="+994 XX XXX XX XX" />
              </div>
            </div>
          </div>

          {/* Description */}
          <div className="bg-white rounded-xl p-6 border">
            <h2 className="text-lg font-semibold mb-4">Təsvir</h2>
            <Textarea
              value={form.description}
              onChange={(e) => setForm({...form, description: e.target.value})}
              placeholder="Əmlak haqqında ətraflı məlumat yazın..."
              rows={6}
            />
          </div>

          {/* Submit */}
          <div className="flex justify-end gap-4">
            <Button type="button" variant="outline" onClick={() => navigate('/')}>Ləğv et</Button>
            <Button type="submit" className="bg-[#B91C1C] hover:bg-[#991B1B]" disabled={isSubmitting}>
              <Save size={18} className="mr-2" />
              {isSubmitting ? 'Yerləşdirilir...' : 'Elanı Yerləşdir'}
            </Button>
          </div>
        </form>
      </main>
    </div>
  );
}
